config/routes.rb
Homeworkio::Application.routes.draw do
  
  resources :homeworks

  resources :lists, :except => [:index, :destroy, :new]

  resources :submissions
  match 'incoming_mime' => "incoming#create"
  
  match "/dj" => DelayedJobWeb, :anchor => false

  devise_for :users, controllers: {registrations: "registrations"}

  match 'db/authorize', :controller => 'dropbox', :action => 'authorize'
  match 'db/upload', :controller => 'dropbox', :action => 'upload'

  root to: "home#index"

end

app/models/list.rb
class List < ActiveRecord::Base
  scope :non_default, where(is_default: false)
  
  def self.default
    where(is_default: true).first
  end

  belongs_to :user
  has_many :students
  has_many :homeworks
  accepts_nested_attributes_for :students, :reject_if => :all_blank, :allow_destroy => true

  def empty?
    students.empty?
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
    @in_wizard = current_user.lists.default == @list && current_user.default_list_empty? 
    @list.students.build
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html {
          if @list.homeworks.empty?
            redirect_to new_homework_path
          else
            redirect_to @list, notice: 'List was successfully updated.' 
          end
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
  def label_for_student(unique_subs, total_subs)
    if unique_subs < total_subs
      'important'
    else
      'success'
    end
  end
  
  def display_for_student(unique_subs, total_subs)
    "#{unique_subs}/#{total_subs}"
  end
end

app/views/lists/_form.html.erb
<%= simple_form_for @list, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= @list.name %></legend>

    <div id="students">
      <%= f.simple_fields_for :students do |s| %>
        <%= render "student_fields", :f => s %>
      <% end %>
    </div>
    <p class="links">
      <%= link_to_add_association "<i class='icon-plus-sign'></i> Add Another Email".html_safe, f, :students, :class => "btn" %>
    </p>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <% if @in_wizard %>
        <%= link_to "skip", new_homework_path, :class => 'btn btn-success'%>
      <%end%>
      <%= link_to 'Cancel', list_path(@list), :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/lists/_student_fields.html.erb
<div class="nested-fields">
  <div class="student-row">
    <%= f.text_field :email, :placeholder => "student@school.edu" %>
    <%= link_to_remove_association "x", f, :class => "close" %>
  </div>
</div>

app/views/lists/edit.html.erb
<% if @in_wizard %>
  <%= render "shared/setup_wizard", :active => "add-students" %>
  <div class="alert alert-info">
    <strong>Don't know your students' emails?:</strong> don't sweat it! You can totally skip this step:
    when your students send an email to submit a homework, if their
    email wasn't on your student list, it will be <em>automatically added</em>
  </div>
<% end %>
<%= render :partial => 'form' %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.id %></td>
        <td><%= link_to list.name, list_path(list) %></td>
        <td><%= list.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_list_path(list), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', list_path(list), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_list_path, :class => 'btn btn-primary' %>

app/views/lists/show.html.erb
<div class="page-header">
  <h1>Students</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Submissions</th>
    </tr>
  </thead>
  <tbody>
    <% @list.students.each do |student| %>
      <tr>
        <td><i class="icon-envelope"></i><%= mail_to student.email %></td>
        <td>
          <span class="label label-<%= label_for_student(student.unique_submissions.count, @list.homeworks.count) %>">
            <%= display_for_student(student.unique_submissions.count, @list.homeworks.count) %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to 'Back', root_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_list_path(@list), :class => 'btn' %>
</div>