config/routes.rb
Homeworkio::Application.routes.draw do
  
  resources :homeworks

  resources :lists, :except => [:index, :destroy, :new]

  resources :submissions
  match 'incoming_mime' => "incoming#create"
  
  match "/dj" => DelayedJobWeb, :anchor => false

  devise_for :users, controllers: {registrations: "registrations"}

  match 'db/authorize', :controller => 'dropbox', :action => 'authorize'
  match 'db/upload', :controller => 'dropbox', :action => 'upload'

  root to: "home#index"

end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :list
  has_many :submissions

  after_create do |homework|
    if homework.should_deliver
      HomeworkMailer.homework_notification(homework).deliver
    end
  end

  def status
    submission_emails = submissions.map{|s| s.student.email}
    if submissions.empty?
      :none
    elsif list.students.map(&:email).all?{|email| submission_emails.include?(email)  }
      :all
    else
      :some
    end
  end

  def email
    "submit+homework#{self.to_param}@homeworkio.com"
  end

  def self.from_address(address)    
    id = /\w+\+homework(?<id>\d+)/.match(address).try(:[], :id)
    find_by_id id
  end

  def teacher
    list.user
  end

  def submissions_by_student
    submissions.group_by &:student
  end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_filter :authenticate_user!

  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = current_user.lists.default.homeworks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homeworks }
    end
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
    @homework = Homework.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @homework }
    end
  end

  # GET /homeworks/new
  # GET /homeworks/new.json
  def new
    @homework = Homework.new
    @homework.deadline = Time.now + 2.hours
    @in_wizard = current_user.lists.default.homeworks.empty?

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @homework }
    end
  end

  # GET /homeworks/1/edit
  def edit
    @homework = Homework.find(params[:id])
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = current_user.lists.default.homeworks.build(params[:homework])

    respond_to do |format|
      if @homework.save
        format.html { redirect_to homeworks_path, notice: 'Homework was successfully created.' }
        format.json { render json: @homework, status: :created, location: @homework }
      else
        format.html { render action: "new" }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homeworks/1
  # PUT /homeworks/1.json
  def update
    @homework = Homework.find(params[:id])

    respond_to do |format|
      if @homework.update_attributes(params[:homework])
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework = Homework.find(params[:id])
    @homework.destroy

    respond_to do |format|
      format.html { redirect_to homeworks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
  def label_for_status(status)
    case status
      when :all then 'success'
      when :some then 'warning'
      when :none then 'important'
    end
  end

  def display_for_status(status)
    case status
      when :all then "All submitted"
      when :some then "Still missing"
      when :none then "No submissions"
    end
  end

  def label_for_submission(on_time)
    if on_time
      'success'
    else
      'important'
    end
  end

  def display_for_submission(on_time)
    if on_time
      "on time"
    else
      "overdue"
    end
  end
end

app/views/homeworks/_form.html.erb
<% if @in_wizard %>
  <%= render "shared/setup_wizard", :active => "first-homework" %>
<% end %>

<%= simple_form_for @homework, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>

    <% unless @in_wizard %>
      <legend>Create new homework</legend>
    <% end %>
    <%= f.input :title %>
    <%= f.input :message, input_html: {:size => "40x5"} %>
    <%= f.input :deadline , wrapper_html: {class: "date-inputs"} %>
    <%= f.input :should_deliver, hint: "Check if you want your students to be automatically notified of this homework"%>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', homeworks_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/homeworks/edit.html.erb
<%= render :partial => 'form' %>

app/views/homeworks/index.html.erb
<div class="page-header">
  <h1>Homeworks</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th>Deadline</th>
      <th>Status</th>
      <th>Mail to</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= link_to homework.title, homework_path(homework) %></td>
        <td><%= homework.message %></td>
        <td><%= l homework.deadline, format: :short %></td>
        <td><span class="label label-<%= label_for_status(homework.status)  %>">
            <%= display_for_status homework.status %>
        </td>
        <td>
          <%= mail_to homework.email  %>
        </td>
        <td>
          <%= link_to 'Edit', edit_homework_path(homework), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', homework_path(homework), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_homework_path, :class => 'btn btn-primary' %>

app/views/homeworks/new.html.erb
<%= render :partial => 'form' %>

app/views/homeworks/show.html.erb
<div class="page-header">
  <h1>Submissions for "<%= @homework.title %>", due <%= l @homework.deadline, format: :short  %></h1>
</div>

<table class="table ">
  <thead>
    <tr>
      <th>From</th>
      <th>Received At</th>
      <th>Attachment</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @homework.submissions_by_student.each do |student, submissions| %>
      <%- 
        ordered = submissions.sort_by(&:created_at).reverse
        head = ordered.first
      -%>

      <% ordered.each do |submission| %>
          <%- is_head = submission == head -%>
          <tr id="submissions_by_<%= student.id %>" class="<%= "duplicate-submission alert" unless is_head %>">

            <td>
              <% if is_head %>
                <%= submission.student.email %>
              <%else%>
                &nbsp;
              <% end%>
            </td>
            <td><%= l submission.created_at, format: :short %></td>
            <td><%= link_to "download", submission.attachment.url %></td>
            <td>
              <span class="label label-<%= label_for_submission(submission.on_time?)%>">
                <%= display_for_submission(submission.on_time?) %>
              </span>
            </td>
            <td>
              <% if ordered.size > 1 && is_head %>
                This entry has more than one submission 
                <%= link_to "(show)", "#dupes", class: "show-dupes", "data-id" => student.id %>
              <% end %>
            </td>
          </tr>                
      <% end %>
    <% end %>
  </tbody>
</table>
<div class="form-actions">
  <%= link_to 'Back', homeworks_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_homework_path(@homework), :class => 'btn' %>
  <%= link_to 'Delete', homework_path(@homework), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>