config/routes.rb
Homeworkio::Application.routes.draw do
  
  resources :homeworks

  resources :lists, :except => [:index, :destroy, :new]

  resources :submissions
  match 'incoming_mime' => "incoming#create"
  
  match "/dj" => DelayedJobWeb, :anchor => false

  devise_for :users, controllers: {registrations: "registrations"}

  match 'db/authorize', :controller => 'dropbox', :action => 'authorize'
  match 'db/upload', :controller => 'dropbox', :action => 'upload'

  root to: "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homeworkio</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <% if false %>
      <link href="images/favicon.ico" rel="shortcut icon">
      <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
      <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
      <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
    <%end%>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Homework.io</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li><%= link_to "Students", list_path(current_user.lists.default)  %></li>
                <li><%= link_to "Homeworks", homeworks_path %></li>
                
                <% unless current_user.db_session %>
                  <li></li>
                <%end%>
              <%end%>
            </ul>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li><%= link_to "<strong>#{current_user.email}</strong>".html_safe, "#" %></li>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
              <%else%>
                <li><%= link_to('Sign Up', new_user_registration_path)  %></li>
                <li><%= link_to('Login', new_user_session_path)  %> </li>
              <%end%>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

    <% flash.each do |name, msg| %>
      <div class="alert notice alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
      <%- show_dropbox_offer = user_signed_in? && !current_user.uses_dropbox? %>
      <div class="content">
        <div class="row">
          <div class="span<%= show_dropbox_offer ? "9" : "12" %> ">
              <%= yield %>
            </div>
            <%if show_dropbox_offer %>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Do you have a dropbox account?</h3>
                <p>
                  You can opt to have your student's homeworks
                  automagically uploaded to your dropbox when they submit them!

                  <strong>Just click the button below and let the magic happen!</strong>
                </p>
                  <%= link_to "Sync Dropbox", db_authorize_path, :class=>'btn-large btn-primary' %>
              </div><!--/.well -->
            </div><!--/span-->
            <%end%>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>